stages:
  - build
  - test
  - package
  - deploy

variables:
  DOCKER_IMAGE: mis-api

build:
  stage: build
  image: gradle:8.5-jdk17-alpine
  script:
    - gradle build -x test
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
    - mis-runner

test:
  stage: test
  image: gradle:8.5-jdk17-alpine
  script:
    - gradle test
  tags:
    - mis-runner

package:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker save $DOCKER_IMAGE:$CI_COMMIT_SHA | gzip > image.tar.gz
  artifacts:
    paths:
      - image.tar.gz
  tags:
    - mis-runner

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp image.tar.gz root@10.1.10.87:/tmp/
    - ssh root@10.1.10.87 "
        docker load < /tmp/image.tar.gz &&
        docker stop app-container || true &&
        docker rm app-container || true &&
        docker run -d --name app-container -p 8080:8080 $DOCKER_IMAGE:$CI_COMMIT_SHA &&
        rm /tmp/image.tar.gz"
  environment: production
  only:
    - main
  tags:
    - mis-runner