stages:
  - build
  - test

variables:
  DOCKER_IMAGE: mis-api
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY  # SSH 개인 키를 GitLab의 환경 변수에서 가져옴
before_script:
  - chmod +x gradlew

build:
  stage: build
  script:
    - echo "build start!"
    - ./gradlew clean
    - ./gradlew build  # Gradle Wrapper를 통해 빌드
  tags:
    - mis-runner

test:
  stage: test
  image: gradle:8.5-jdk17-alpine
  script:
    - echo "test start!"
  tags:
    - mis-runner
  dependencies:
    - build

