stages:
  - build
  - docker-build
  - docker-push
  - test

variables:
  DOCKER_IMAGE: mis-api
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2375  # DinD 서비스 주소
  DOCKER_TLS_VERIFY: "0"
  DOCKER_CERT_PATH: "/certs/client"
  REGISTRY_URL: $REGISTRY_URL  # GitLab Container Registry URL
  REGISTRY_USER: $REGISTRY_USER  # GitLab 사용자 이름
  REGISTRY_PASSWORD: $REGISTRY_PASSWORD  # Access Token

before_script:
  - chmod +x gradlew  # gradlew에 실행 권한 부여

build:
  stage: build
  image: gradle:8.5-jdk17-apline
  script:
    - echo "build start!"
    - export JAVA_HOME=/opt/javaj/openjdk
    - export PATH=$JAVA_HOME/bin:$PATH
    - ./gradlew clean
    - ./gradlew build  # Gradle Wrapper를 통해 빌드
  tags:
    - mis-runner

docker-build:
  stage: docker-build
  image: docker:stable
  services:
    - name: docker:dind
      alias: docker
  script:
    - echo "Docker build start!"
    - docker build -t $REGISTRY_URL/mis-api/$DOCKER_IMAGE:$CI_COMMIT_REF_NAME .
  tags:
    - mis-runner
  dependencies:
    - build

docker-push:
  stage: docker-push
  image: docker:stable
  services:
    - name: docker:dind
      alias: docker
  script:
    - echo "Docker push start!"
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker push $REGISTRY_URL/mis-api/$DOCKER_IMAGE:$CI_COMMIT_REF_NAME
  tags:
    - mis-runner
  dependencies:
    - docker-build

test:
  stage: test
  image: gradle:8.5-jdk17-alpine
  script:
    - echo "test start!"
  tags:
    - mis-runner
  dependencies:
    - build
