spring:
  application:
    name: mis
  datasource:
    url: jdbc:mariadb://10.1.10.216:3306/mis  # 마리아DB 연결 URL
    username: user  # 데이터베이스 사용자 이름
    password: kmi12345  # 데이터베이스 비밀번호
    driver-class-name: org.mariadb.jdbc.Driver  # 마리아DB JDBC 드라이버 클래스
    jpa:
      database-platform: org.hibernate.dialect.MariaDBDialect  # JPA 데이터베이스 플랫폼 설정
      hibernate:
        ddl-auto: update  # Hibernate 자동 DDL 설정 (옵션)
    show-sql: true  # 쿼리 로그를 JPA 레벨에서도 출력
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
        use_sql_comments: true  # SQL에 주석 추가
        cache:
          use_second_level_cache: false  # 2차 캐시 비활성화
          use_query_cache: false         # 쿼리 캐시 비활성화
logging:
  level:
    org:
      springframework:
        transaction: info
        orm:
          jpa: info
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace
      hibernate:
        type:
          descriptor:
            sql: info
    web: info
    root: info
server:
  port: 9090