spring:
  application:
    name: mis
  datasource:
    url: jdbc:mariadb://10.1.10.216:3306/mis  # ???DB ?? URL
    username: user  # ?????? ??? ??
    password: kmi12345  # ?????? ????
    driver-class-name: org.mariadb.jdbc.Driver  # ???DB JDBC ???? ???
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect  # JPA ?????? ??? ??
    hibernate:
      ddl-auto: update  # Hibernate ?? DDL ?? (??)

logging:
  level:
    org:
      springframework:
        transaction: info
        orm:
          jpa: info
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace
      hibernate:
        type:
          descriptor:
            sql: info
    web: info
    root: info

server:
  port: 9090
